### ISSUE TITLE
Installing instrain

### ISSUE THREAD

**Issue by joshmanuel8** [michaelwoodworth/practicalmetagenomics#10]
Hey Michael,

Having trouble installing instrain. Conda was taking forever so I tried pip and tried from the source code, both of which threw this error 

× Encountered error while trying to install package.
╰─> biopython

I installed biopython with conda separately and that didn't seem to fix anything. I will leave conda spinning overnight to see if it resolves, but any suggestions? Couldn't find many potential fixes online.

Thanks,
Josh

**Comment by michaelwoodworth** [comment]
That's interesting, I don't think I've ever had trouble with installing inStrain but have only done it a few times. I just tried to create a new test environment to install it and it looks like I'm getting the same error(s) you are with pip, conda, and installing from source... 

Babiker recently was able to install it on the cluster at Ga Tech, I wonder if he knows a solution.

It's not ideal but I'll try to upload some output files to OneDrive so we can look at them together and imagine what it would be like to have inStrain running... If we don't find a group solution tomorrow to run inStrain, it is probably worth posting an issue for biopython.

**Comment by michaelwoodworth** [comment]
i think we sorted out that this was a resolved issue with inStrain (though I may have lost the link). Will close for now.
