### ISSUE TITLE
Uploading pm06s file to server 

### ISSUE THREAD

**Issue by natalie0lson** [michaelwoodworth/practicalmetagenomics#2]
```
Hi! I'm trying to get the data file uploaded to the server but I'm not sure how to format the server path. 

Here is what I entered (and got an error that says "bad substitution"):
 rsync -avzhe ssh --progress ${C:\Users\nmolson\OneDrive - Emory University\Shared Drives\23.01.22 - Metagenomics # Directed Study\Data} ${nmolson}${EMORYServerIPAddress}:${/home/nmolson/anaconda3/envs/myenv}
```

**Comment by michaelwoodworth** [comment]
Hi! Sorry about that, sorry about the confusing placeholders, was trying to limit server/user specifics on the web. Also, bash/linux environments don't work well with spaces so I've added quotes around your path, which should work.  

Also, you probably want to create a directory to work with files in that is separate from the conda environment files. 

To do this, get back to your home directory
`cd ~`

And make a new directory
`mkdir data`

And then try this but replacing the 999.999.999.999 with our IP address:

rsync -avzhe ssh --progress "C:\Users\nmolson\OneDrive - Emory University\Shared Drives\23.01.22 - Metagenomics # Directed Study\Data" nmolson@999.999.999.999:/home/nmolson/data/PM06S.tar.gz

**Comment by natalie0lson** [comment]
``Thanks! I ran that but it returned the error "the source and destination cannot both be remote" - do you know why the destination file would be recognized as remote? From what I can see online any pathname with a colon i.e. "C: " is recognized as remote, but I haven't been able to identify any workarounds.

**Comment by michaelwoodworth** [comment]
Oh yes, sorry, that is going to be a PC issue... It's a little hard to know if you can use a different path. when you list your working directory from your terminal client with `pwd` does that still start with C:\... ? If not, you could use that path. If it still starts with C:... then you may want to try to use a GUI client. I think a lot of PC users use PuTTY (https://www.hostknox.com/tutorials/ssh/putty/file-transfer). You should be able to adjust it to transfer with ssh and your login credentials.

**Comment by natalie0lson** [comment]
Thanks! Apologies for all the troubleshooting issues, but I've installed PuTTY and followed a tutorial to transfer files, but I've been getting the following error - do you know why permission would be denied?

**Comment by michaelwoodworth** [comment]
Arg - sorry, not sure. I don't think it will give you a login prompt if not on VPN so assume that's not the issue, and assuming it's not the password....

On second look, it seems that [CyberDuck](https://cyberduck.io) is also available on PC so maybe that will be easier. Can you try to download that and see if it will let you log in using your credentials when on the VPN?

We'll get there!

ps - I deleted the screenshot in your comment since it lists our IP address and your username

**Comment by natalie0lson** [comment]
Thanks! Win SCP ended up working :)
