### ISSUE TITLE
Running trimmomatic with example code

### ISSUE THREAD

**Issue by mnadim01** [michaelwoodworth/practicalmetagenomics#3]
I had some trouble running the example trimmomatic code but realized (eventually) that there were some typos. Posting here in case anyone had similar issues:
#ID
ID=PM6-S

#Values for R1 and R2:
R1=${indir}/${ID}_R1.fastq
R2=${indir}/${ID}_R2.fastq

Lastly, I had to create a /summary_files directory in the outdir location in order for the code to run correctly.

**Comment by michaelwoodworth** [comment]
thank you! i think i have updated the markdown.
