### ISSUE TITLE
Bracken error message - "illegal option --w" 

### ISSUE THREAD

**Issue by natalie0lson** [michaelwoodworth/practicalmetagenomics#5]
![image](https://user-images.githubusercontent.com/106370813/217982637-6ef0f37c-7b78-466f-b950-ba3ee0108f37.png)

I think it's an issue with where the kraken output is stored but wanted to see if you had any other insight. Thanks!

**Comment by michaelwoodworth** [comment]
1) will it run if you leave out the `-w ${outdir}/${ID}_${level}.kb` argument?

2) if you run `bracken -h` (or `bracken --help` if `-h` doesn't work), does it list -w as an argument it accepts? if not, is there an alternative flag that will write a new kraken-style report after read counts are reestimated? i think the kraken-biom tool expects kraken report input but the combine_bracken_output.py script will still work with just the `.bracken` output.

**Comment by michaelwoodworth** [comment]
Hi everyone, trying to look into this a bit more. I reinstalled bracken in a new test environment (version 2.8) and when I run `bracken -h` I am still getting the option to provide a -w argument:

```
(bracken_test) [mwoodworth8@atl1-1-02-010-19-2 slurm]$ bracken -h
/storage/home/hcoda1/0/mwoodworth8/.conda/envs/bracken_test/bin/bracken: illegal option -- h
Usage: bracken -d MY_DB -i INPUT -o OUTPUT -w OUTREPORT -r READ_LEN -l LEVEL -t THRESHOLD
  MY_DB          location of Kraken database
  INPUT          Kraken REPORT file to use for abundance estimation
  OUTPUT         file name for Bracken default output
  OUTREPORT      New Kraken REPORT output file with Bracken read estimates
  READ_LEN       read length to get all classifications for (default: 100)
  LEVEL          level to estimate abundance at [options: D,P,C,O,F,G,S,S1,etc] (default: S)
  THRESHOLD      number of reads required PRIOR to abundance estimation to perform reestimation (default: 0)
```

This makes me wonder if everyone has the latest version of bracken? Did the folks who are having trouble with the -w flag install with conda or another source? Was it with the [bioconda channel](https://anaconda.org/bioconda/bracken) or another channel?

**Comment by natalie0lson** [comment]
I installed with conda / bioconda channel - can try re-installing and see if that does anything

**Comment by michaelwoodworth** [comment]
closing for now.
