### ISSUE TITLE
Code comment

### ISSUE THREAD

**Issue by babikera** [michaelwoodworth/practicalmetagenomics#6]
Hi Mike 

In your kraken code you havent specified the outdir

kraken2 --db $db --threads 20 --output ${ID}.kraken2 --report ${ID}.kreport --paired ${indir}/${ID}_P1.fastq ${indir}/${ID}_P2.fastq

I think it should be 

kraken2 --db $db --threads 20 --output  ${outdir}/${ID}.kraken2 --report  ${outdir}${ID}.kreport --paired ${indir}/${ID}_P1.fastq ${indir}/${ID}_P2.fastq

**Comment by michaelwoodworth** [comment]
Thanks! I think I've corrected it now.
