### ISSUE TITLE
bracken_names=(`ls *.bracken | cut -d. -f1`)

### ISSUE THREAD

**Issue by joshmanuel8** [michaelwoodworth/practicalmetagenomics#7]
Hey Michael,

It took me a while but I figured out I needed to do (`ls $indir/*.bracken | cut -d. -f1`) to make the combine function work on multiple bracken files. That being said, my tsv file still has the entire path to the braken file as opposed to just the name in the column header. Any quick fix for that, for now I will just edit the tsv?

Thanks,
Josh

**Comment by michaelwoodworth** [comment]
thanks, i've updated that step to include `${indir}/*.bracken`.

when you run `echo ${bracken_names[@]}`, do you get just the sample names or does that print the whole path for each bracken file? i think that is the variable that the script uses to label the column headers.

**Comment by joshmanuel8** [comment]
It gives me the paths, is there a way to trim that or am I naming those variables incorrectly?

**Comment by michaelwoodworth** [comment]
dangit. what happens if you first change into the input directory (`cd ${indir}`) and run the array step with `*.bracken` without the `${indir}/*.bracken` prefix?

**Comment by michaelwoodworth** [comment]
the other option that could be useful if it doesn't work to run within the directory where the files are stored, would be to try the command basename, which should be able to give you just the file name without the path.
