### ISSUE TITLE
sample_names(sampledata)  <- sample_names(OTU)

### ISSUE THREAD

**Issue by joshmanuel8** [michaelwoodworth/practicalmetagenomics#8]
For phyloseq, I am getting this error when I run the above code

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

It looks like the PREMIX_metadata.csv file has 99 names and OTU from PREMIX_mg_biom.json has 293 causing the error. 

Am I getting a step wrong before this that is throwing this error? This is my code:

########### import data
# import biom file to phyloseq
# see https://www.cell.com/cms/10.1016/j.isci.2020.100905/attachment/d3d5d291-4f11-4ecf-af92-558af5d1f474/mmc7
biom_path   <-"/Users/levinlabuser/Desktop/Michael Practical Genomics/"    # double check you have a "/" at the end of this value
data        <- import_biom(paste0(biom_path,"PREMIX_mg_biom.json"), parseFunction=parse_taxonomy_default)
md          <- read_csv(paste0(biom_path, "PREMIX_metadata.csv"))

# list of PREMIX participants who completed at least one cycle & donor
PREMIX_ID_list <- c("PM01",
                    "PM02",
                    "PM03",
                    "PM04",
                    "PM05",
                    "PM06",
                    "PM07",
                    "PM08",
                    "PM09",
                    "PM12",
                    "PM13",
                    "SD01")

########### prepare data
# prepare sample data (i.e. metadata) for storage in phyloseq object
sampledata  <- sample_data(md)

# pull OTU table from imported biom file
OTU         <- otu_table(data@otu_table, taxa_are_rows = TRUE)

# pull taxonomy table from imported biom file
TAX         <- tax_table(data@tax_table)

# use OTU table sample names to label sample data object
sample_names(sampledata)  <- sample_names(OTU)

Thanks,
Josh

**Comment by michaelwoodworth** [comment]
Hi Josh (and everyone) - I think the issue this time was on my end. I have uploaded a biom file that should better match the metadata. Can you either refresh your OneDrive folder or download the biom file again?

**Comment by natalie0lson** [comment]
I'm still getting 99 names from sampledata and 98 from OTU (getting closer!)

**Comment by michaelwoodworth** [comment]
thanks for hanging in there. 

i deleted the extra row in the metadata file, should be current in the OneDrive folder. i tried to just rerun the code and made a couple of other minor corrections.

if you set your `biom_path` and `metadata_path` and work with the files in OneDrive, let's cross fingers and try again!

**Comment by michaelwoodworth** [comment]
closing this issue, i think we got it sorted.
